# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  install_dependencies:
    steps:
    # See: https://github.com/Spotifyd/spotifyd/issues/183
      - run:
          name: Install libsdl2-dev
          command: 'sudo apt-get install libsdl2-dev'
# Use a package of configuration called an orb.
orbs:
  rust: glotrade/rust@0.1.3
# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - install_dependencies
      - rust/test
